### ISSUE TITLE
Error "package maps is not in GOROOT" during revive install

### ISSUE THREAD

**Issue by Clivern** [mgechev/revive#1068]
**Describe the bug**
I get this error "package maps is not in GOROOT"

**To Reproduce**

```shell
# flags

revive ...
$ go version go1.20.4 darwin/amd64

$ go install github.com/mgechev/revive@latest
go: downloading github.com/mgechev/revive v1.4.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/fatih/color v1.1[7](https://github.com/Clivern/Goenv/actions/runs/11485909202/job/31967054190?pr=101#step:4:8).0
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/BurntSushi/toml v1.4.0
go: downloading github.com/mgechev/dots v0.0.0-20210922191527-e955255bf517
go: downloading github.com/chavacava/garif v0.1.0
go: downloading github.com/olekukonko/tablewriter v0.0.5
go: downloading github.com/hashicorp/go-version v1.7.0
go: downloading golang.org/x/mod v0.20.0
go: downloading github.com/fatih/structtag v1.2.0
go: downloading golang.org/x/tools v0.24.0
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/mattn/go-runewidth v0.0.9
go: downloading golang.org/x/sys v0.23.0
Error: ../../../go/pkg/mod/github.com/mgechev/revive@v1.4.0/rule/redefines-builtin-id.go:7:2: package maps is not in GOROOT (/opt/hostedtoolcache/go/1.20.14/x64/src/maps)
note: imported by a module that requires go 1.21
make: *** [Makefile:1[8](https://github.com/Clivern/Goenv/actions/runs/11485909202/job/31967054190?pr=101#step:4:9): install_revive] Error 1
```

```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
```

**Expected behavior**
It should work

**Desktop (please complete the following information):**
 - Golang 1.18, 1.19, 1.20
 - Ubuntu, Mac OS
