### ISSUE TITLE
Configuration option to ignore error handling with early return linter

### ISSUE THREAD

**Issue by Jacobbrewer1** [mgechev/revive#1253]
**Is your feature request related to a problem? Please describe.**

When using the early return option, it will pick up on the traditional Go error handling of

```go
if err != nil {
    return err
}
```

Which then causes a pollution of 

```
// nolint:revive // Traditional error handling
```

throughout the codebase.

**Describe the solution you'd like**

I would like to see an additional configuration argument come to the early return linter that allows for error handling statements to be excluded by the linter.

**Describe alternatives you've considered**

I have tried to add exclude statements to the rule to prevent this from returning an error, but this has had no success; additionally this is very restrictive and bound to a single handling of errors.

Config:

```yaml
      - name: early-return
        severity: error
        disabled: false
        exclude: [ "if err != nil {" ]
        arguments:
          - "preserveScope"
          - "allowJump"
```

Output:
```
❯ golangci-lint run
client.go:106:2: early-return: if c { ... } can be rewritten if !c { return } ... to reduce nesting (revive)
        if err != nil {
                slog.Error("unable to renew auth info", slog.String(loggingKeyError, err.Error()))
                os.Exit(1)
        }
```

**Additional context**

N/a

**Comment by chavacava** [comment]
Hi @Jacobbrewer1, thanks for the proposal.

Could you please provide an example of:
1. the source code under analysis
2. the `revive` configuration
3. the result of running `revive` with that configuration on the source code

I've ran `revive` with the following configuration

```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.early-return]
  arguments = ["preserveScope", "allowJump"]
```

on

```go
package revive

func foo() error {
	err := bar()
	if err != nil {
		return err
	}

	return nil
}
```

and `revive` reports nothing.

**Comment by Jacobbrewer1** [comment]
Hi @chavacava 

Sure, here is some more info.

This is one of the trigger places with the code that is being triggered

```go
func (c *client) renewAuthInfo() {
	err := RenewLease(c.ctx, c, "auth", c.authCreds, func() (*hashiVault.Secret, error) {
		authInfo, err := c.auth(c.v)
		if err != nil {
			return nil, fmt.Errorf("unable to renew auth info: %w", err)
		}

		c.authCreds = authInfo

		return authInfo, nil
	})
	if err != nil {
		slog.Error("unable to renew auth info", slog.String(loggingKeyError, err.Error()))
		os.Exit(1)
	}
}
```

The revive configuration lives within the golangci lint config, which is as follows

```yaml
linters:
  enable:
    - revive
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - revive
      text: "^(enforce-slice-style|enforce-map-style)"
linters-settings:
  revive:
    # Default: false
    ignore-generated-header: true
    # Default: 0.8
    confidence: 0.1
    rules:
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#context-as-argument
      - name: context-as-argument
        severity: error
        disabled: false
        exclude: [ "" ]
        arguments:
          - allowTypesBefore: "*testing.T"
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#early-return
      - name: early-return
        severity: error
        disabled: false
        exclude: [ "" ]
        arguments:
          - "preserveScope"
          - "allowJump"
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#enforce-map-style
      - name: enforce-map-style
        severity: error
        disabled: false
        exclude: [ "" ]
        arguments:
          - "make"
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#enforce-slice-style
      - name: enforce-slice-style
        severity: error
        disabled: false
        exclude: [ "" ]
        arguments:
          - "make"
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#filename-format
      - name: filename-format
        severity: error
        disabled: false
        exclude: [ "" ]
        arguments:
          - "^[_a-z][_a-z0-9]*.go$"
      # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#optimize-operands-order
      - name: optimize-operands-order
        severity: error
        disabled: false
        exclude: [ "" ]
```

With the above examples, when golangci-lint is ran, it produces the following

```bash
❯ golangci-lint run
client.go:106:2: early-return: if c { ... } can be rewritten if !c { return } ... to reduce nesting (revive)
        if err != nil {
                slog.Error("unable to renew auth info", slog.String(loggingKeyError, err.Error()))
                os.Exit(1)
        }
```

---

### Update

I have found another example in another repo of mine

```go
// MustEncode encodes a response as JSON and logs an error if it fails
func MustEncode[T any](w http.ResponseWriter, status int, v T) {
	if err := Encode(w, status, v); err != nil { // nolint:revive // This is traditional Go error handling
		slog.Error("Error encoding response", slog.String(loggingKeyError, err.Error()))
		return
	}
}
```
