### ISSUE TITLE
`rule.unhandled-error` does not work for nested methods

### ISSUE THREAD

**Issue by jBugman** [mgechev/revive#350]
**Describe the bug**
Consider some abstract function/method `ReturnsError() error`
There are three general cases how it could be called
1. `ReturnsError()` — catches ok
2. `struct.ReturnsError()` — catches ok
3. `struct.field.ReturnsError()` — ignored by revive

**To Reproduce**
```toml
[rule.unhandled-error]
  arguments = ["fmt.Printf"]
  severity = "error"
```

**Expected behavior**
Rule should work for all described cases.
