### ISSUE TITLE
Expose the ability to enable all rules

### ISSUE THREAD

**Issue by Zamiell** [mgechev/revive#517]
Hello, and thanks for the linter. I have a feature request.

Right now, it appears that the only way that users can enable all rules and disable one rule is to manually specify every single existing rule into the config except for the one specific one that they don't want.

This is tedious, and not very future proof.
Meaning that when you guys add a new useful rule, I don't want to have to manually do research and find out which specific new rule that you added, and then manually add that new rule to my config in order to stay up-to-date. I just want to upgrade my version of `golangci-lint` and automatically get the latest and greatest linting without having to change my config.

As an analogy, golangci-lint allows this kind of workflow with the following YML config:

```yml
linters:
  enable-all: true
  disable:
    # These linters are deprecated
    - interfacer
    - maligned
    - scopelint
```

**Comment by chavacava** [comment]
Hi @Zamiell, thanks for filling the issue.

This is a subject that we had already talked about (for example #104 and #236) but for which we were not able to find a nice solution.

There are some aspects to take into account:
1. some rules need config (they will fail if not provided)...
2. ...using defaults config for those rules is possible but finding _good_ defaults is hard (or impossible) because there are some very opinionated settings (for example: `argument-limit`, `cyclomatic` and the like)

**Comment by Zamiell** [comment]
I think that both 1 and 2 are fine.

Here's a hypothetical user story:

1) Alice enables `revive` for the first time through golangci-lint. (She also disables `golint`, which she was previously using).

2) Alice finds `revive` useful. But she realizes that she actually wants to disable the `exported` rule and keep everything else.

3) Alice adds the following to her .golangci.yml file:

```yml
linters-settings:
  revive:
    enable-all: true
    rules:
     - name: exported
       severity: disabled
```

4) Upon running the program again, Alice is greeted with an error message:
`rule A, B, and C need a default config and none was specified.`

5) Based on their names, Alice knows that she doesn't actually care about rule A, B, or C. So instead of bothering to specify a config, she decides that it will be quicker to just disable them. Alice changes her .golangci.yml file again:

```yml
linters-settings:
  revive:
    enable-all: true
    rules:
     - name: exported
       severity: disabled
     - name: A
       severity: disabled
     - name: B
       severity: disabled
     - name: C
       severity: disabled
```

6) Upon running the program again, the error message is fixed! But now, Alice sees that rules D, E, and F generate a ton of noise across her code-base.
- This is partly because D and E are opinionated settings and finding good defaults for them is hard.
- F doesn't fall under this category. F has good defaults, but in this case, F is just a legitimately spurious rule that Alice doesn't care about.
Alice changes her .golangci.yml file again to disable D, E, and F:

```yml
linters-settings:
  revive:
    enable-all: true
    rules:
     - name: exported
       severity: disabled
     - name: A
       severity: disabled
     - name: B
       severity: disabled
     - name: C
       severity: disabled
     - name: D
       severity: disabled
     - name: E
       severity: disabled
     - name: F
       severity: disabled
```

7) Now, `revive` is only generating a few messages, and these expose actual problems in Alice's codebase. The tuning process is over. Alice is satisfied with `revive` and decides to keep using it in the future.

8) Furthermore, Alice is happy that her "rules" config for `revive` is only around 14 lines long. It would be unwieldy and terrible if Alice had to copy paste 50+ rules into her config one by one, and then be burdened with keeping it up-to-date whenever the maintainers of `revive` decided to add another new rule.

One could argue that in this hypothetical, Alice is *still* burdened with keeping her config up-to-date, because as soon as the maintainers of `revive` add another annoying rule that she doesn't care about, then Alice has to go add yet-another-entry to her rule blacklist, and she is stuck in a cycle of updating it with more entries.

However, I  don't think this is a valid criticism. Implicitly, by specifying `enable-all: true`, Alice is communicating that by default, she usually finds new linters/rules valuable. Alice needing to add a new entry to blacklist is the *exception* rather than the norm. And in the hypothetical where Alice becomes exasperated by a torrent of new rules, she always has the freedom to remove the `enable-all: true` entry and "invert" her config, so to speak.

**Comment by chavacava** [comment]
@Zamiell, please check [this branch](https://github.com/mgechev/revive/tree/all-rules) and let me know if it fits your expectations.

The _all-rules-activated_ configuration looks something like:

```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0
activateAllRules = true # here we activate all rules

# Deactivated rules
[rule.blank-imports]
    Deactivated = true
[rule.file-header]
    Deactivated = true
[rule.max-public-structs]
    Deactivated = true
[rule.line-length-limit]
    Deactivated = true
[rule.function-length]
    Deactivated = true

# Rule tuning
[rule.argument-limit]
    Arguments = [5]
[rule.cyclomatic]    
    Arguments = [10]
[rule.cognitive-complexity]    
    Arguments = [7]
[rule.function-result-limit]    
    Arguments = [3]
```
