### ISSUE TITLE
Enable all linters doesnt enable all linters?

### ISSUE THREAD

**Issue by DGollings** [mgechev/revive#617]
**Describe the bug**
```
linters:
  enable-all: true
```

Doesn't appear to enable revive

Changing that to
```
linters:
  enable-all
  enable:
    - revive
```

Fixes it (as in, it now errors)

I've manually disabled 30 other linters so I take it 'enable all' does enable plenty. Just seemingly not all all :)

Had a quick look in the codebase, I can't tell if this is a bug or feature though

**To Reproduce**

Have some go code that would trigger a rule, exported is an easy one
```
  linters:
    enable-all: true
  revive:
    # see https://github
    ignore-generated-hea
    severity: error
    confidence: 0.8
    errorCode: 1
    warningCode: 2
    rules:
      - name: exported
  ```
  vs
  ```
  linters:
    enable-all: true
    enable:
    - revive
  revive:
    # see https://github
    ignore-generated-hea
    severity: error
    confidence: 0.8
    errorCode: 1
    warningCode: 2
    rules:
      - name: exported
  ```
