### ISSUE TITLE
Cannot find certain rules

### ISSUE THREAD

**Issue by ricenzca** [mgechev/revive#621]
**Describe the bug**
Cannot find the following rules:
- time-equal
- banned-characters
- optimize-operands-order

**To Reproduce**
1. I installed revive `go install github.com/mgechev/revive@latest`
2. I run it with the following flags & configuration file:

```shell
revive -formatter friendly -config default.toml ./...
```

```toml
# When set to false, ignores files with "GENERATED" header, similar to golint
ignoreGeneratedHeader = true

# Sets the default severity to "warning"
severity = "warning"

# Sets the default failure confidence. This means that linting errors
# with less than 0.8 confidence will be ignored.
confidence = 0.8

# Sets the error code for failures with severity "error"
errorCode = 1

# Sets the error code for failures with severity "warning"
warningCode = 1

[rule.time-equal]
[rule.banned-characters]
[rule.optimize-operands-order]
```

**Expected behavior**
I expect the rule to be present and executed

**Logs**
![image](https://user-images.githubusercontent.com/48046395/149486497-ab4dc333-5960-4bbb-8560-b34f2ca17b3c.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version of Go: 1.16.8

**Additional context**
NA
