### ISSUE TITLE
[rule.import-blacklist] should allow check tests

### ISSUE THREAD

**Issue by chen3feng** [mgechev/revive#732]
**Is your feature request related to a problem? Please describe.**
Hi, I' using revive to check my team's project, it's great.

I want to disable an unmaintained and archived package, but it doesn't work:

```toml
[rule.imports-blacklist]
arguments = ["bou.ke/monkey"]
```

So I checked the source code and found that:

```go
	if file.IsTest() {
		return failures // skip, test file
	}

```

**Describe the solution you'd like**
I don't know why this design, but at least it should be configurable.

Thanks!
