### ISSUE TITLE
Rule `add-constant` is not working

### ISSUE THREAD

**Issue by marek-valuch** [mgechev/revive#752]
**Describe the bug**
Arguments in rule `add-constant` doesn't work

```
/home/...: avoid magic numbers like '0', create a named constant for it (revive)
/home/...: avoid magic numbers like '1', create a named constant for it (revive)
/home/...: avoid magic numbers like '2', create a named constant for it (revive)
/home/...: string literal "" appears, at least, 3 times, create a named constant for it (revive)
/home/...: string literal "" appears, at least, 3 times, create a named constant for it (revive)
```

**To Reproduce**
Use `golang-ci` version 1.5 with following config

```
Config:
  revive:
     ...
    rules: 
      - name: add-constant
        severity: warning
        arguments:
          - maxLitCount: "10"
            allowStrs: '""'
            allowInts: "0,1,2,3"
            allowFloats: "0.0,0.,1.0,1.,2.0,2."
```
**Expected behavior**
No warnings expected

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Go version: 1.19.1

**Additional context**
In `golang-ci` version 1.49 these warnings doesn't occur.
