### ISSUE TITLE
Can not disable ID var-naming

### ISSUE THREAD

**Issue by oslyak** [mgechev/revive#774]
**Describe the bug**
Can not disable ID var-naming

**To Reproduce**

.golangci.yml
```
  revive:
    rules:
      - name: "var-naming"
        arguments: [["Id", "ID"], ["VM"]]
```

How should file be named?
revive or revive.toml ????

```toml
[rule.var-naming]
    Disabled = true
```
