### ISSUE TITLE
Missing tag "latest" on container images uploaded to ghcr.io

### ISSUE THREAD

**Issue by echoix** [mgechev/revive#786]
**Describe the bug**

The container images stored on GitHub (ghcr.io) do not contain the latest tag. It is only possible to get a specific version tag.

**To Reproduce**
1. Run `docker pull ghcr.io/mgechev/revive`
2. See error
 ```
docker pull ghcr.io/mgechev/revive
Using default tag: latest
Error response from daemon: manifest unknown
```
3. See available packages on https://github.com/mgechev/revive/pkgs/container/revive

**Expected behavior**
Be able to get the latest release with ghcr.io/mgechev/revive:latest

**Logs**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Version of Go

**Additional context**

**Comment by echoix** [comment]
The solution would be to edit the release.yml https://github.com/mgechev/revive/blob/a4f4632a3f934868012008d36eecafb912282d45/.github/workflows/release.yml
in order to have another tag:

So change this:
```yaml
dockers:
- image_templates: ["ghcr.io/mgechev/revive:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mgechev/revive
  - --label=org.opencontainers.image.source=https://github.com/mgechev/revive
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
```
To this:
```yaml
dockers:
  - image_templates: 
    - "ghcr.io/mgechev/revive:{{ .Version }}"
    - "ghcr.io/mgechev/revive:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.source=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
```
