### ISSUE TITLE
How to configure `upperCaseConst` for the `var-naming` rule within `golangci-lint` for revive?

### ISSUE THREAD

**Issue by takanuva15** [mgechev/revive#893]
**Describe the bug**
I'm confused how to configure `upperCaseConst` for the `var-naming` rule within `golangci-lint` for revive. The [linter-setting documentation](https://golangci-lint.run/usage/linters#revive) in golangci-lint only shows 2 arguments for the `var-naming` rule. How would I specify the `upperCaseConst` option?

I tried this but it doesn't seem to work with the golangci-lint GitHub action. It still tells me to remove ALL_CAPS constants:
```
linters-settings:
  revive:
    rules:
      - name: var-naming
        arguments:
          - []
          - []
          - [{upperCaseConst=true}]
```

**To Reproduce**
The Github action output is in a company repo so I can't link it here. I'm just wondering whether it's even possible to specify `upperCaseConst` through golangci-lint?

**Expected behavior**
I should be able to specify the option

**Logs**
```
  Error: models/file.go:14:7: var-naming: don't use ALL_CAPS in Go names; use CamelCase (revive)
  const MY_SPECIAL = "Spec"
        ^
  
  Error: issues found
```

**Desktop (please complete the following information):**
 - OS: MacOS 13.4
 - Go 1.20

**Additional context**
